version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0